"""phase_m_strategy_pine_webhook_columns

Adds 4 new columns to the strategies table for pine_webhook support:
  - pine_code      TEXT    nullable  — stores latest Pine Script code (display only)
  - timeframe      VARCHAR nullable  — e.g. "1h", "4h", "1D"
  - current_version INTEGER NOT NULL — version counter (bumped on each pine save)
  - is_test_mode   BOOLEAN NOT NULL  — if True, signals logged but never executed

NOTE: The autogenerated migration also detected UUID type changes across all tables.
Those are SQLite-only artefacts (CHAR(32) vs VARCHAR(36)) and are NOT applied here.
In production (PostgreSQL) UUIDs are stored natively; the previous migration handles them.

Revision ID: a76ca8c8ef7b
Revises: dd4e6834c773
Create Date: 2026-07-21 10:52:12.099326

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a76ca8c8ef7b'
down_revision: Union[str, None] = 'dd4e6834c773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Add Phase M pine_webhook columns to strategies table.
    Uses batch_alter_table for SQLite compatibility (SQLite cannot ALTER COLUMN).
    """
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('pine_code', sa.Text(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('timeframe', sa.String(length=10), nullable=True)
        )
        batch_op.add_column(
            sa.Column('current_version', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('is_test_mode', sa.Boolean(), nullable=False, server_default='0')
        )


def downgrade() -> None:
    """Remove the 4 Phase M columns from strategies table."""
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_column('is_test_mode')
        batch_op.drop_column('current_version')
        batch_op.drop_column('timeframe')
        batch_op.drop_column('pine_code')
