"""initial_schema

Revision ID: fd08d116da93
Revises: 7b1e99e847b8
Create Date: 2026-07-19 00:06:41.211387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database


# revision identifiers, used by Alembic.
revision: str = 'fd08d116da93'
down_revision: Union[str, None] = '7b1e99e847b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_events',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('impact', sa.String(length=10), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast', sa.String(length=100), nullable=True),
    sa.Column('previous', sa.String(length=100), nullable=True),
    sa.Column('actual', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_events_event_time'), 'economic_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_economic_events_external_id'), 'economic_events', ['external_id'], unique=True)
    op.create_table('users',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('alert_deliveries',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', app.database.UUIDType(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_deliveries_user_id'), 'alert_deliveries', ['user_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('threshold', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_count', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_user_id'), 'alert_rules', ['user_id'], unique=False)
    op.create_table('chat_threads',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_chat_thread_user')
    )
    op.create_table('journal_entries',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('mood', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('login_activity',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_activity_user_id'), 'login_activity', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('risk_rules',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_count', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_rules_user_id'), 'risk_rules', ['user_id'], unique=False)
    op.create_table('telegram_configs',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=False),
    sa.Column('bot_token_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_configs_user_id'), 'telegram_configs', ['user_id'], unique=True)
    op.create_table('user_exchange_accounts',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('exchange_id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_consent', sa.Boolean(), nullable=False),
    sa.Column('billing_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("sync_status IN ('pending','connected','syncing','error','stale')", name='ck_exchange_account_sync_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_exchange_accounts_user_id'), 'user_exchange_accounts', ['user_id'], unique=False)
    op.create_table('user_profit_periods',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_realized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('performance_fee_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('performance_fee_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('open','estimated','acknowledged','paid','waived','incomplete')", name='ck_profit_period_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_start', name='uq_profit_period_user_start')
    )
    op.create_index(op.f('ix_user_profit_periods_user_id'), 'user_profit_periods', ['user_id'], unique=False)
    op.create_table('balances',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('exchange_account_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('wallet_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('margin_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['user_exchange_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_account_id', 'asset', name='uq_balance_account_asset')
    )
    op.create_index(op.f('ix_balances_exchange_account_id'), 'balances', ['exchange_account_id'], unique=False)
    op.create_table('billing_period_records',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('profit_period_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('exchange_account_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('account_realized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('data_complete', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['user_exchange_accounts.id'], ),
    sa.ForeignKeyConstraint(['profit_period_id'], ['user_profit_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profit_period_id', 'exchange_account_id', name='uq_billing_record_period_account')
    )
    op.create_index(op.f('ix_billing_period_records_profit_period_id'), 'billing_period_records', ['profit_period_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('thread_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_table('encrypted_api_credentials',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('exchange_account_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('encrypted_api_secret', sa.Text(), nullable=False),
    sa.Column('encrypted_passphrase', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['user_exchange_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encrypted_api_credentials_exchange_account_id'), 'encrypted_api_credentials', ['exchange_account_id'], unique=True)
    op.create_table('exchange_billing_consents',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('exchange_account_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('consent_granted', sa.Boolean(), nullable=False),
    sa.Column('consent_version', sa.String(length=20), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['user_exchange_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_billing_consents_exchange_account_id'), 'exchange_billing_consents', ['exchange_account_id'], unique=False)
    op.create_index(op.f('ix_exchange_billing_consents_user_id'), 'exchange_billing_consents', ['user_id'], unique=False)
    op.create_table('exchange_sync_runs',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('exchange_account_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('sync_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('triggered_by', sa.String(length=30), nullable=False),
    sa.CheckConstraint("status IN ('running','success','error','partial')", name='ck_sync_run_status'),
    sa.CheckConstraint("sync_type IN ('balances','positions','trades','full')", name='ck_sync_run_type'),
    sa.CheckConstraint("triggered_by IN ('scheduler','manual','webhook')", name='ck_sync_run_triggered_by'),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['user_exchange_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_sync_runs_exchange_account_id'), 'exchange_sync_runs', ['exchange_account_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('exchange_account_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('binance_order_id', sa.String(length=50), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('reduce_only', sa.Boolean(), nullable=False),
    sa.Column('time_in_force', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('avg_fill_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['user_exchange_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_binance_order_id'), 'orders', ['binance_order_id'], unique=False)
    op.create_index(op.f('ix_orders_exchange_account_id'), 'orders', ['exchange_account_id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('positions',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('exchange_account_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('mark_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('leverage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('margin_type', sa.String(length=20), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['user_exchange_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_account_id', 'symbol', 'side', name='uq_position_account_symbol_side')
    )
    op.create_index(op.f('ix_positions_exchange_account_id'), 'positions', ['exchange_account_id'], unique=False)
    op.create_table('risk_violations',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('rule_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('action_taken', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['risk_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_violations_rule_id'), 'risk_violations', ['rule_id'], unique=False)
    op.create_index(op.f('ix_risk_violations_user_id'), 'risk_violations', ['user_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('exchange_account_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('order_side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('reduce_only', sa.Boolean(), nullable=False),
    sa.Column('price_level', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('max_executions', sa.Integer(), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['user_exchange_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_symbol'), 'strategies', ['symbol'], unique=False)
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('exchange_account_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('binance_trade_id', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('qty', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('commission_asset', sa.String(length=20), nullable=False),
    sa.Column('is_maker', sa.Boolean(), nullable=True),
    sa.Column('trade_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['user_exchange_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_account_id', 'binance_trade_id', name='uq_trade_account_binance_id')
    )
    op.create_index(op.f('ix_trades_exchange_account_id'), 'trades', ['exchange_account_id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_trade_time'), 'trades', ['trade_time'], unique=False)
    op.create_table('strategy_executions',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('strategy_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('order_id', app.database.UUIDType(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_executions_strategy_id'), 'strategy_executions', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_strategy_executions_user_id'), 'strategy_executions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_executions_user_id'), table_name='strategy_executions')
    op.drop_index(op.f('ix_strategy_executions_strategy_id'), table_name='strategy_executions')
    op.drop_table('strategy_executions')
    op.drop_index(op.f('ix_trades_trade_time'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_exchange_account_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_symbol'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_risk_violations_user_id'), table_name='risk_violations')
    op.drop_index(op.f('ix_risk_violations_rule_id'), table_name='risk_violations')
    op.drop_table('risk_violations')
    op.drop_index(op.f('ix_positions_exchange_account_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_exchange_account_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_binance_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_exchange_sync_runs_exchange_account_id'), table_name='exchange_sync_runs')
    op.drop_table('exchange_sync_runs')
    op.drop_index(op.f('ix_exchange_billing_consents_user_id'), table_name='exchange_billing_consents')
    op.drop_index(op.f('ix_exchange_billing_consents_exchange_account_id'), table_name='exchange_billing_consents')
    op.drop_table('exchange_billing_consents')
    op.drop_index(op.f('ix_encrypted_api_credentials_exchange_account_id'), table_name='encrypted_api_credentials')
    op.drop_table('encrypted_api_credentials')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_billing_period_records_profit_period_id'), table_name='billing_period_records')
    op.drop_table('billing_period_records')
    op.drop_index(op.f('ix_balances_exchange_account_id'), table_name='balances')
    op.drop_table('balances')
    op.drop_index(op.f('ix_user_profit_periods_user_id'), table_name='user_profit_periods')
    op.drop_table('user_profit_periods')
    op.drop_index(op.f('ix_user_exchange_accounts_user_id'), table_name='user_exchange_accounts')
    op.drop_table('user_exchange_accounts')
    op.drop_index(op.f('ix_telegram_configs_user_id'), table_name='telegram_configs')
    op.drop_table('telegram_configs')
    op.drop_index(op.f('ix_risk_rules_user_id'), table_name='risk_rules')
    op.drop_table('risk_rules')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_login_activity_user_id'), table_name='login_activity')
    op.drop_table('login_activity')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_alert_rules_user_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_alert_deliveries_user_id'), table_name='alert_deliveries')
    op.drop_table('alert_deliveries')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_economic_events_external_id'), table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_event_time'), table_name='economic_events')
    op.drop_table('economic_events')
    # ### end Alembic commands ###
