"""phase_m_strategy_webhook_tables

Revision ID: dd4e6834c773
Revises: f68d12b15a4b
Create Date: 2026-07-20 15:11:58.372249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database


# revision identifiers, used by Alembic.
revision: str = 'dd4e6834c773'
down_revision: Union[str, None] = 'f68d12b15a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_event_outbox',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_status_created', 'domain_event_outbox', ['status', 'created_at'], unique=False)
    op.create_table('strategy_audit_log',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('strategy_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', app.database.UUIDType(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_audit_log_strategy_id'), 'strategy_audit_log', ['strategy_id'], unique=False)
    op.create_table('strategy_pine_versions',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('strategy_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('pine_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'version_number', name='uq_pine_version_per_strategy')
    )
    op.create_index(op.f('ix_strategy_pine_versions_strategy_id'), 'strategy_pine_versions', ['strategy_id'], unique=False)
    op.create_table('strategy_signals',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('strategy_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('strategy_version', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=30), nullable=False),
    sa.Column('contracts', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('tv_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('sender_ip', sa.String(length=45), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('order_id', app.database.UUIDType(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_strategy_signals_status_received', 'strategy_signals', ['status', 'received_at'], unique=False)
    op.create_index(op.f('ix_strategy_signals_strategy_id'), 'strategy_signals', ['strategy_id'], unique=False)
    op.create_index('ix_strategy_signals_strategy_received', 'strategy_signals', ['strategy_id', 'received_at'], unique=False)
    op.create_index(op.f('ix_strategy_signals_user_id'), 'strategy_signals', ['user_id'], unique=False)
    op.create_index('ix_strategy_signals_user_received', 'strategy_signals', ['user_id', 'received_at'], unique=False)
    op.create_table('strategy_targets',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('strategy_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('exchange_account_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['user_exchange_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'exchange_account_id', name='uq_target_per_strategy')
    )
    op.create_index(op.f('ix_strategy_targets_strategy_id'), 'strategy_targets', ['strategy_id'], unique=False)
    op.create_table('strategy_webhook_secrets',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('strategy_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('secret_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rotated_from_id', app.database.UUIDType(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_webhook_secrets_strategy_id'), 'strategy_webhook_secrets', ['strategy_id'], unique=False)
    op.create_table('execution_records',
    sa.Column('id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('signal_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('strategy_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('user_id', app.database.UUIDType(length=36), nullable=False),
    sa.Column('risk_result', sa.String(length=10), nullable=False),
    sa.Column('risk_rule_id', app.database.UUIDType(length=36), nullable=True),
    sa.Column('order_id', app.database.UUIDType(length=36), nullable=True),
    sa.Column('execution_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['strategy_signals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_records_signal_id'), 'execution_records', ['signal_id'], unique=True)
    op.create_index(op.f('ix_execution_records_strategy_id'), 'execution_records', ['strategy_id'], unique=False)
    op.alter_column('alert_deliveries', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('alert_deliveries', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('alert_deliveries', 'rule_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=True)
    op.alter_column('alert_rules', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('alert_rules', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('balances', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('balances', 'exchange_account_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('billing_period_records', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('billing_period_records', 'profit_period_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('billing_period_records', 'exchange_account_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('billing_period_records', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('chat_messages', 'thread_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('chat_threads', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('chat_threads', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('economic_events', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('encrypted_api_credentials', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('encrypted_api_credentials', 'exchange_account_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('exchange_billing_consents', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('exchange_billing_consents', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('exchange_billing_consents', 'exchange_account_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('exchange_sync_runs', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('exchange_sync_runs', 'exchange_account_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('journal_entries', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('journal_entries', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('login_activity', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('login_activity', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('orders', 'exchange_account_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('positions', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('positions', 'exchange_account_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('risk_rules', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('risk_rules', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('risk_violations', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('risk_violations', 'rule_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('risk_violations', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.add_column('strategies', sa.Column('pine_code', sa.Text(), nullable=True))
    op.add_column('strategies', sa.Column('timeframe', sa.String(length=10), nullable=True))
    op.add_column('strategies', sa.Column('current_version', sa.Integer(), nullable=False))
    op.add_column('strategies', sa.Column('is_test_mode', sa.Boolean(), nullable=False))
    op.alter_column('strategies', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('strategies', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('strategies', 'exchange_account_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('strategies', 'order_side',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('strategies', 'quantity',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    op.alter_column('strategy_executions', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('strategy_executions', 'strategy_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('strategy_executions', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('strategy_executions', 'order_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=True)
    op.alter_column('telegram_configs', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('telegram_configs', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('trades', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('trades', 'exchange_account_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('user_exchange_accounts', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('user_exchange_accounts', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('user_profit_periods', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('user_profit_periods', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.database.UUIDType(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_profit_periods', 'user_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_profit_periods', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_exchange_accounts', 'user_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_exchange_accounts', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('trades', 'exchange_account_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('trades', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('telegram_configs', 'user_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('telegram_configs', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('strategy_executions', 'order_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('strategy_executions', 'user_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('strategy_executions', 'strategy_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('strategy_executions', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('strategies', 'quantity',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    op.alter_column('strategies', 'order_side',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('strategies', 'exchange_account_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('strategies', 'user_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('strategies', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_column('strategies', 'is_test_mode')
    op.drop_column('strategies', 'current_version')
    op.drop_column('strategies', 'timeframe')
    op.drop_column('strategies', 'pine_code')
    op.alter_column('risk_violations', 'user_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('risk_violations', 'rule_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('risk_violations', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('risk_rules', 'user_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('risk_rules', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('positions', 'exchange_account_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('positions', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('orders', 'exchange_account_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('login_activity', 'user_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('login_activity', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('journal_entries', 'user_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('journal_entries', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('exchange_sync_runs', 'exchange_account_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('exchange_sync_runs', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('exchange_billing_consents', 'exchange_account_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('exchange_billing_consents', 'user_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('exchange_billing_consents', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('encrypted_api_credentials', 'exchange_account_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('encrypted_api_credentials', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('economic_events', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('chat_threads', 'user_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('chat_threads', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('chat_messages', 'thread_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('chat_messages', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('billing_period_records', 'user_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('billing_period_records', 'exchange_account_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('billing_period_records', 'profit_period_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('billing_period_records', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('balances', 'exchange_account_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('balances', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('alert_rules', 'user_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('alert_rules', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('alert_deliveries', 'rule_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('alert_deliveries', 'user_id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('alert_deliveries', 'id',
               existing_type=app.database.UUIDType(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_index(op.f('ix_execution_records_strategy_id'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_signal_id'), table_name='execution_records')
    op.drop_table('execution_records')
    op.drop_index(op.f('ix_strategy_webhook_secrets_strategy_id'), table_name='strategy_webhook_secrets')
    op.drop_table('strategy_webhook_secrets')
    op.drop_index(op.f('ix_strategy_targets_strategy_id'), table_name='strategy_targets')
    op.drop_table('strategy_targets')
    op.drop_index('ix_strategy_signals_user_received', table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_user_id'), table_name='strategy_signals')
    op.drop_index('ix_strategy_signals_strategy_received', table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_strategy_id'), table_name='strategy_signals')
    op.drop_index('ix_strategy_signals_status_received', table_name='strategy_signals')
    op.drop_table('strategy_signals')
    op.drop_index(op.f('ix_strategy_pine_versions_strategy_id'), table_name='strategy_pine_versions')
    op.drop_table('strategy_pine_versions')
    op.drop_index(op.f('ix_strategy_audit_log_strategy_id'), table_name='strategy_audit_log')
    op.drop_table('strategy_audit_log')
    op.drop_index('ix_outbox_status_created', table_name='domain_event_outbox')
    op.drop_table('domain_event_outbox')
    # ### end Alembic commands ###
